name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - 'test/*'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx xo

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm run demo:build

  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - firefox
        permission:
          - tabs
          - webNavigation
        version:
          - "2"
          - "3"
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install xvfb
      - run: npm ci
      - run: npm run demo:build
      - name: Use tabs-only permission
        if: matrix.permission == 'tabs'
        run: |
          sed -i 's/webNavigation/tabs/' test/demo-extension/mv${{ matrix.version }}/manifest.json
      - run: xvfb-run --auto-servernum npm run jest:core
        env:
          TARGET: ${{ matrix.version }}
          BROWSER: ${{ matrix.browser }}
