name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - 'test/*'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npx xo

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm run demo:build

  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run vitest

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install xvfb
      - run: npm ci
      - run: npm run demo:build
      - run: xvfb-run --auto-servernum npm run jest:core
